package cli

import (
	"fmt"
	"strconv"

	"github.com/spf13/cobra"

	"danny.vn/s1/mgmt"
)

func newAccountsReactivateCmd() *cobra.Command {
	var (
		unlimited  bool
		expiration string
		yes        bool
	)
	cmd := &cobra.Command{
		Use:   "reactivate <account-id>",
		Short: "Reactivate an expired account",
		Long: `Reactivate an expired account. Specify exactly one of --unlimited (no
expiration) or --expiration (an RFC3339 timestamp) to set the new license
window.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			if err := validateReactivateChoice(unlimited, expiration); err != nil {
				return err
			}
			return guard(cmd.OutOrStdout(), "accounts reactivate", "reactivate account "+id, id, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				if err := c.AccountsReactivate(cmd.Context(), id, unlimited, expiration); err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), map[string]string{"status": "reactivated", "id": id})
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Reactivated account %s\n", id)
				return nil
			})
		},
	}
	cmd.Flags().BoolVar(&unlimited, "unlimited", false, "reactivate with no expiration")
	cmd.Flags().StringVar(&expiration, "expiration", "", "new expiration as an RFC3339 timestamp")
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}

func newAccountsExpireCmd() *cobra.Command {
	var yes bool
	cmd := &cobra.Command{
		Use:   "expire <account-id>",
		Short: "Expire an account immediately",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			return guard(cmd.OutOrStdout(), "accounts expire", "expire account "+id, id, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				if err := c.AccountsExpireNow(cmd.Context(), id); err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), map[string]string{"status": "expired", "id": id})
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Expired account %s\n", id)
				return nil
			})
		},
	}
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}

func newAccountsUninstallPasswordCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "uninstall-password",
		Short: "Manage an account's agent uninstall password",
	}
	requireSubcommand(cmd)
	cmd.AddCommand(newUninstallPasswordShowCmd())
	cmd.AddCommand(newUninstallPasswordGenerateCmd())
	cmd.AddCommand(newUninstallPasswordRevokeCmd())
	return cmd
}

func newUninstallPasswordShowCmd() *cobra.Command {
	var metadataOnly bool
	cmd := &cobra.Command{
		Use:   "show <account-id>",
		Short: "Show an account's uninstall password",
		Long: `Print an account's current uninstall password to stdout. The password is
sensitive secret material. Pass --metadata to print only non-secret metadata
(version, expiration, who generated/revoked it).`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			c, err := mgmtClient()
			if err != nil {
				return err
			}
			if metadataOnly {
				return uninstallPasswordShowMetadata(cmd, c, id)
			}
			pw, err := c.AccountsUninstallPasswordView(cmd.Context(), id)
			if err != nil {
				return err
			}
			if outputFormat == "json" {
				if err := printJSON(cmd.OutOrStdout(), pw); err != nil {
					return err
				}
			} else {
				fmt.Fprintln(cmd.OutOrStdout(), pw.Password)
			}
			noteSensitiveOutput(cmd.ErrOrStderr())
			return nil
		},
	}
	cmd.Flags().BoolVar(&metadataOnly, "metadata", false, "show non-secret metadata instead of the password")
	return markJSON(cmd)
}

func uninstallPasswordShowMetadata(cmd *cobra.Command, c *mgmt.Client, id string) error {
	meta, err := c.AccountsUninstallPasswordMetadata(cmd.Context(), id)
	if err != nil {
		return err
	}
	if outputFormat == "json" {
		return printJSON(cmd.OutOrStdout(), meta)
	}
	rows := [][]string{
		{"Version", strconv.Itoa(meta.Version)},
		{"Expiration", orDash(meta.Expiration)},
		{"Created", orDash(meta.CreatedAt)},
		{"Generated By", orDash(meta.GeneratedByName)},
		{"Last Revoked", orDash(meta.LastRevoked)},
		{"Revoked By", orDash(meta.RevokedByName)},
	}
	printTable([]string{"Field", "Value"}, rows)
	return nil
}

func newUninstallPasswordGenerateCmd() *cobra.Command {
	var expiration string
	var yes bool
	cmd := &cobra.Command{
		Use:   "generate <account-id>",
		Short: "Generate a new uninstall password",
		Long: `Generate (or regenerate) an account's uninstall password. --expiration
(yyyy-mm-dd) is required. On apply, the new password is read back and printed to
stdout — treat it as a secret. If the follow-up read fails, the password was
still rotated and can be retrieved with "uninstall-password show".`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			if expiration == "" {
				return fmt.Errorf("--expiration is required")
			}
			return guard(cmd.OutOrStdout(), "accounts uninstall-password generate", "generate uninstall password for account "+id, id, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				if _, err := c.AccountsUninstallPasswordGenerate(cmd.Context(), id, expiration); err != nil {
					return err
				}
				pw, err := c.AccountsUninstallPasswordView(cmd.Context(), id)
				if err != nil {
					return err
				}
				if outputFormat == "json" {
					if err := printJSON(cmd.OutOrStdout(), pw); err != nil {
						return err
					}
				} else {
					fmt.Fprintln(cmd.OutOrStdout(), pw.Password)
				}
				noteSensitiveOutput(cmd.ErrOrStderr())
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&expiration, "expiration", "", "password expiration date, yyyy-mm-dd (required)")
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}

func newUninstallPasswordRevokeCmd() *cobra.Command {
	var yes bool
	cmd := &cobra.Command{
		Use:   "revoke <account-id>",
		Short: "Revoke an account's uninstall password",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			return guard(cmd.OutOrStdout(), "accounts uninstall-password revoke", "revoke uninstall password for account "+id, id, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				if err := c.AccountsUninstallPasswordRevoke(cmd.Context(), id); err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), map[string]string{"status": "revoked", "id": id})
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Revoked uninstall password for account %s\n", id)
				return nil
			})
		},
	}
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}
