package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"danny.vn/s1/mgmt"
)

func newUpdatesDeployCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "deploy",
		Short: "Manage Sentinel Deploy credential groups",
		Long: `Manage credential groups used by Sentinel Deploy (Ranger auto-deploy)
to install agents on unprotected endpoints.

Credential groups contain encrypted credentials that agents use to
authenticate when deploying to new endpoints.`,
	}
	requireSubcommand(cmd)
	cmd.AddCommand(newDeployCredGroupListCmd())
	cmd.AddCommand(newDeployCredGroupCreateCmd())
	cmd.AddCommand(newDeployCredGroupDeleteCmd())
	cmd.AddCommand(newDeployCredDetailListCmd())
	cmd.AddCommand(newDeployCredDetailAddCmd())
	cmd.AddCommand(newDeployCredDetailUpdateCmd())
	cmd.AddCommand(newDeployCredDetailDeleteCmd())
	return cmd
}

func newDeployCredGroupListCmd() *cobra.Command {
	var (
		siteIDs    []string
		accountIDs []string
		groupName  string
		targetOS   string
		cursor     string
		sortBy     string
		sortOrder  string
		limit      int
		all        bool
	)

	cmd := &cobra.Command{
		Use:   "list-groups",
		Short: "List credential groups",
		RunE: func(cmd *cobra.Command, _ []string) error {
			c, err := mgmtClient()
			if err != nil {
				return err
			}
			params := &mgmt.DeployCredGroupListParams{
				SiteIDs:       siteIDs,
				AccountIDs:    accountIDs,
				GroupNameLike: groupName,
				TargetOS:      targetOS,
				Cursor:        cursor,
				SortBy:        sortBy,
				SortOrder:     sortOrder,
				Limit:         limit,
			}
			if params.Limit == 0 {
				params.Limit = defaultPageSize
			}

			var items []mgmt.DeployCredGroup
			var total int

			if all {
				items, total, err = fetchAllREST("cred group", func(cur string) ([]mgmt.DeployCredGroup, *mgmt.Pagination, error) {
					params.Cursor = cur
					return c.DeployCredGroupList(cmd.Context(), params)
				})
			} else {
				var pag *mgmt.Pagination
				items, pag, err = c.DeployCredGroupList(cmd.Context(), params)
				if pag != nil {
					total = pag.TotalItems
				}
			}
			if err != nil {
				return err
			}

			headers := []string{"ID", "Name", "Domain", "OS", "Scope ID", "Details"}
			rows := make([][]string, len(items))
			for i, g := range items {
				rows[i] = []string{
					g.ID, g.GroupName, orDash(g.Domain),
					string(g.TargetOS), g.ScopeID,
					fmt.Sprintf("%d", g.TotalDetails),
				}
			}
			return printOutput(cmd.OutOrStdout(), headers, rows, items, len(items), total, "cred group", all)
		},
	}
	cmd.Flags().StringSliceVar(&siteIDs, "site-id", nil, "filter by site ID")
	cmd.Flags().StringSliceVar(&accountIDs, "account-id", nil, "filter by account ID")
	cmd.Flags().StringVar(&groupName, "group-name", "", "filter by group name (substring)")
	cmd.Flags().StringVar(&targetOS, "target-os", "", "filter by target OS (windows|osx_linux)")
	cmd.Flags().IntVar(&limit, "limit", 0, "max results per page (default 50)")
	cmd.Flags().BoolVar(&all, "all", false, "fetch all pages")
	cmd.Flags().StringVar(&cursor, "cursor", "", "pagination cursor")
	cmd.Flags().StringVar(&sortBy, "sort-by", "", "sort field (groupName|createdAt|updatedAt|domain|targetOs)")
	cmd.Flags().StringVar(&sortOrder, "sort-order", "", "sort direction (asc|desc)")
	return markJSON(cmd)
}

func newDeployCredGroupCreateCmd() *cobra.Command {
	var (
		groupName       string
		groupPassphrase string
		scopeID         string
		domain          string
		targetOS        string
		yes             bool
	)

	cmd := &cobra.Command{
		Use:   "create-group",
		Short: "Create a credential group",
		Long: `Create a new Sentinel Deploy credential group.

The passphrase is an encrypted value generated by the agent; the
management console does not know the decryption key.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if groupName == "" {
				return fmt.Errorf("--group-name is required")
			}
			if groupPassphrase == "" {
				return fmt.Errorf("--group-passphrase is required")
			}
			if scopeID == "" {
				return fmt.Errorf("--scope-id is required")
			}

			input := mgmt.DeployCredGroupCreateInput{
				GroupName:       groupName,
				GroupPassphrase: groupPassphrase,
				ScopeID:         scopeID,
			}
			if domain != "" {
				input.Domain = &domain
			}
			if targetOS != "" {
				os := mgmt.DeployTargetOS(targetOS)
				input.TargetOS = &os
			}

			action := fmt.Sprintf("create cred group %q (scope=%s)", groupName, scopeID)
			return guard(cmd.OutOrStdout(), "updates deploy create-group", action, groupName, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				g, err := c.DeployCredGroupCreate(cmd.Context(), input)
				if err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), g)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Created cred group %s (%s)\n", g.ID, g.GroupName)
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&groupName, "group-name", "", "credential group name")
	cmd.Flags().StringVar(&groupPassphrase, "group-passphrase", "", "encrypted passphrase")
	cmd.Flags().StringVar(&scopeID, "scope-id", "", "scope ID (site ID)")
	cmd.Flags().StringVar(&domain, "domain", "", "domain associated with the group")
	cmd.Flags().StringVar(&targetOS, "target-os", "", "target OS (windows|osx_linux)")
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}

func newDeployCredGroupDeleteCmd() *cobra.Command {
	var yes bool

	cmd := &cobra.Command{
		Use:   "delete-group <cred-group-id>",
		Short: "Delete a credential group",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			return guard(cmd.OutOrStdout(), "updates deploy delete-group", "delete cred group "+id, id, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				if err := c.DeployCredGroupDelete(cmd.Context(), id); err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), map[string]string{"status": "deleted", "id": id})
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Deleted cred group %s\n", id)
				return nil
			})
		},
	}
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}

func newDeployCredDetailListCmd() *cobra.Command {
	var (
		siteIDs      []string
		credGroupIDs []string
		title        string
		cursor       string
		sortBy       string
		sortOrder    string
		limit        int
		all          bool
	)

	cmd := &cobra.Command{
		Use:   "list-details",
		Short: "List credential group details",
		RunE: func(cmd *cobra.Command, _ []string) error {
			c, err := mgmtClient()
			if err != nil {
				return err
			}
			params := &mgmt.DeployCredDetailListParams{
				SiteIDs:      siteIDs,
				CredGroupIDs: credGroupIDs,
				TitleLike:    title,
				Cursor:       cursor,
				SortBy:       sortBy,
				SortOrder:    sortOrder,
				Limit:        limit,
			}
			if params.Limit == 0 {
				params.Limit = defaultPageSize
			}

			var items []mgmt.DeployCredDetail
			var total int

			if all {
				items, total, err = fetchAllREST("cred detail", func(cur string) ([]mgmt.DeployCredDetail, *mgmt.Pagination, error) {
					params.Cursor = cur
					return c.DeployCredDetailList(cmd.Context(), params)
				})
			} else {
				var pag *mgmt.Pagination
				items, pag, err = c.DeployCredDetailList(cmd.Context(), params)
				if pag != nil {
					total = pag.TotalItems
				}
			}
			if err != nil {
				return err
			}

			headers := []string{"ID", "Group ID", "Title", "Type", "Created"}
			rows := make([][]string, len(items))
			for i, d := range items {
				rows[i] = []string{
					d.ID, d.CredGroupID, d.Title, d.CredType, d.CreatedAt,
				}
			}
			return printOutput(cmd.OutOrStdout(), headers, rows, items, len(items), total, "cred detail", all)
		},
	}
	cmd.Flags().StringSliceVar(&siteIDs, "site-id", nil, "filter by site ID")
	cmd.Flags().StringSliceVar(&credGroupIDs, "cred-group-id", nil, "filter by credential group ID")
	cmd.Flags().StringVar(&title, "title", "", "filter by title (substring)")
	cmd.Flags().IntVar(&limit, "limit", 0, "max results per page (default 50)")
	cmd.Flags().BoolVar(&all, "all", false, "fetch all pages")
	cmd.Flags().StringVar(&cursor, "cursor", "", "pagination cursor")
	cmd.Flags().StringVar(&sortBy, "sort-by", "", "sort field (title|type|createdAt|updatedAt|credType)")
	cmd.Flags().StringVar(&sortOrder, "sort-order", "", "sort direction (asc|desc)")
	return markJSON(cmd)
}

func newDeployCredDetailAddCmd() *cobra.Command {
	var (
		credGroupID   string
		title         string
		credType      string
		encryptedKey  string
		encryptedCred string
		yes           bool
	)

	cmd := &cobra.Command{
		Use:   "add-detail",
		Short: "Add a credential detail to a group",
		RunE: func(cmd *cobra.Command, _ []string) error {
			if credGroupID == "" {
				return fmt.Errorf("--cred-group-id is required")
			}
			if title == "" {
				return fmt.Errorf("--title is required")
			}
			if credType == "" {
				return fmt.Errorf("--cred-type is required")
			}
			if encryptedKey == "" {
				return fmt.Errorf("--encrypted-key is required")
			}
			if encryptedCred == "" {
				return fmt.Errorf("--encrypted-cred is required")
			}

			action := fmt.Sprintf("add cred detail %q to group %s", title, credGroupID)
			return guard(cmd.OutOrStdout(), "updates deploy add-detail", action, title, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				err = c.DeployCredDetailAdd(cmd.Context(), mgmt.DeployCredDetailAddInput{
					CredGroupID: credGroupID,
					Details: []mgmt.DeployCredDetailInput{
						{
							Title:         title,
							CredType:      credType,
							EncryptedKey:  encryptedKey,
							EncryptedCred: encryptedCred,
						},
					},
				})
				if err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), map[string]string{"status": "added", "credGroupId": credGroupID})
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Added cred detail %q to group %s\n", title, credGroupID)
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&credGroupID, "cred-group-id", "", "credential group ID")
	cmd.Flags().StringVar(&title, "title", "", "credential title")
	cmd.Flags().StringVar(&credType, "cred-type", "", "credential type (e.g. User/Password)")
	cmd.Flags().StringVar(&encryptedKey, "encrypted-key", "", "encrypted key")
	cmd.Flags().StringVar(&encryptedCred, "encrypted-cred", "", "encrypted credential")
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}

func newDeployCredDetailUpdateCmd() *cobra.Command {
	var (
		title         string
		credType      string
		encryptedKey  string
		encryptedCred string
		yes           bool
	)

	cmd := &cobra.Command{
		Use:   "update-detail <detail-id>",
		Short: "Update a credential detail",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			if title == "" {
				return fmt.Errorf("--title is required")
			}
			if credType == "" {
				return fmt.Errorf("--cred-type is required")
			}
			if encryptedKey == "" {
				return fmt.Errorf("--encrypted-key is required")
			}
			if encryptedCred == "" {
				return fmt.Errorf("--encrypted-cred is required")
			}

			action := fmt.Sprintf("update cred detail %s (title=%q)", id, title)
			return guard(cmd.OutOrStdout(), "updates deploy update-detail", action, id, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				d, err := c.DeployCredDetailUpdate(cmd.Context(), id, mgmt.DeployCredDetailInput{
					Title:         title,
					CredType:      credType,
					EncryptedKey:  encryptedKey,
					EncryptedCred: encryptedCred,
				})
				if err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), d)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Updated cred detail %s\n", id)
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&title, "title", "", "credential title")
	cmd.Flags().StringVar(&credType, "cred-type", "", "credential type")
	cmd.Flags().StringVar(&encryptedKey, "encrypted-key", "", "encrypted key")
	cmd.Flags().StringVar(&encryptedCred, "encrypted-cred", "", "encrypted credential")
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}

func newDeployCredDetailDeleteCmd() *cobra.Command {
	var yes bool

	cmd := &cobra.Command{
		Use:   "delete-detail <detail-id>",
		Short: "Delete a credential detail",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			return guard(cmd.OutOrStdout(), "updates deploy delete-detail", "delete cred detail "+id, id, yes, func() error {
				c, err := mgmtClient()
				if err != nil {
					return err
				}
				if err := c.DeployCredDetailDelete(cmd.Context(), id); err != nil {
					return err
				}
				if outputFormat == "json" {
					return printJSON(cmd.OutOrStdout(), map[string]string{"status": "deleted", "id": id})
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Deleted cred detail %s\n", id)
				return nil
			})
		},
	}
	cmd.Flags().BoolVar(&yes, "yes", false, "apply the action (default: dry-run)")
	return markJSON(cmd)
}
